/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EndNode: typeof import('./../components/nodes/EndNode.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    LlmNode: typeof import('./../components/nodes/LlmNode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartNode: typeof import('./../components/nodes/StartNode.vue')['default']
  }
}
